### ISSUE TITLE
Fancybox JS error in backend

### ISSUE THREAD

**Issue by esedic** [getk2/k2#412]
After updating K2 to 2.8.0 I'm getting this error in console in item view:

`Uncaught TypeError: e.fancybox.getInstance is not a function
at HTMLDocument.<anonymous> (jquery.fancybox.min.js:12)
at HTMLDocument.dispatch (jquery.min.js?81428951fab52f3688f6271610fa99c3:3)
at HTMLDocument.r.handle (jquery.min.js?81428951fab52f3688f6271610fa99c3:3)`

**Comment by esedic** [comment]
Update: I think there is a conflict with SIG Pro, which also loads fancybox in the backend, but older version.

**Comment by fevangelou** [comment]
Are you referring to the frontend or backend item view?

**Comment by fevangelou** [comment]
(BTW, SIGPro will soon be updated with the latest FancyBox release...)
